apiVersion: v1
baseDomain: example.com
proxy:
  httpProxy: http://utility.ocp.example.com:3128
  httpsProxy: http://utility.ocp.example.com:3128
  noProxy: example.com,192.168.155.0/24
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '!EDIT ME paste your pull secret from cloud.redhat.com'
sshKey: '!EDIT ME Generate an ssh key on utility and copy it here. TODO'