apiVersion: v1
baseDomain: kahvi.online
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  .........................
  -----END CERTIFICATE-----
pullSecret: '{"auths":{"utility.ocp.kahvi.online:5000":{"auth":"YWVyZGVpOnIzZGg0dA=="}}}'
imageContentSources:
- mirrors:
  - utility.ocp.kahvi.online:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - utility.ocp.kahvi.online:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
sshKey: 'UtilitySSHKeyHere'
