apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  curl http://192.168.122.53:8080/domain.crt
  -----END CERTIFICATE-----
pullSecret: '{"auths":{"utility.ocp.example.com:5000":{"auth":"b2NwOm9jcA==","email":"admin@ocp.example.com"}}}'
imageContentSources:
- mirrors:
  - utility.ocp.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - utility.ocp.example.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
sshKey: 'Generate an ssh key on utility and copy it here. TODO'