apiVersion: v1
baseDomain: kahvi.online
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIGITCCBAmgAwIBAgIUAvAXI4A/Sh7r5QA+YxxW55pSt48wDQYJKoZIhvcNAQEL
  BQAwgZ8xCzAJBgNVBAYTAlNFMRIwEAYDVQQIDAlTdG9ja2hvbG0xEjAQBgNVBAcM
  CUhhZ2Vyc3RlbjEQMA4GA1UECgwHUmVkIEhhdDERMA8GA1UECwwIU2VydmljZXMx
  ITAfBgNVBAMMGHN1cHBvcnQub2NwLmthaHZpLm9ubGluZTEgMB4GCSqGSIb3DQEJ
  ARYRYWVyZGVpQHJlZGhhdC5jb20wHhcNMTkxMDMwMDkzMzU0WhcNMjAxMDI5MDkz
  MzU0WjCBnzELMAkGA1UEBhMCU0UxEjAQBgNVBAgMCVN0b2NraG9sbTESMBAGA1UE
  BwwJSGFnZXJzdGVuMRAwDgYDVQQKDAdSZWQgSGF0MREwDwYDVQQLDAhTZXJ2aWNl
  czEhMB8GA1UEAwwYc3VwcG9ydC5vY3Aua2Fodmkub25saW5lMSAwHgYJKoZIhvcN
  AQkBFhFhZXJkZWlAcmVkaGF0LmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
  AgoCggIBAMKIGi3irJ13mfIXl25LcEekH0qDSbRjeB6rigyKuIvddQ05aZvlU4LP
  UOUrG9FkOv/7FAJUS9UpAOA29F8yQLhlKkYPvM9JkBT3fg1CVKwYrM/y/i6X2SWB
  C9dVFTDMn1IhnNgZIITkYGu54AdiMLeQK4/jTw4/9BXEAmqQ7c21kOahYQ25KSS9
  Y/W4HI39etDineSRPI/InGfjHxyriT/+DmClS1Dln8akUDdM8SuMCyJtT9K8RV82
  IBmtvkVt1kdKZmQBCtBdxm+a/d+8n/GFj3u6ZOhT3LByIr/rIF1XDX2FInCkd3dX
  cjNGAmieztkxttGAdTiBUvhs60iCTTIPQ11fAX2S3RKE0OEW2RlhhlSYUzd3W6Qd
  I3uo6D5JcWahEG8zCcNHq20psz3GlJb99CrwcNYF5Kt5QLR5rMs54Sux1lPEE3ph
  P/EReY90KOC/J3PYJ1n1RGUzEd9nHw3LM/TJy67p7pYnV50Md3o2xJEgCiI/aOqZ
  ExVxzsjveETrAChhW/lkcNfLRcvCPFHvApb6wWsXYX8rA8oTPFH2ZIBRCkiGbUPD
  bZS3JhaKjas1qlCJh3tKdRqUBFCyJO5zlXGUMNIhcy9Ep2bgJEs/ijXryoVZWdze
  YJA0Ql8eNBvEcK5XMO/rF7WLEfkkXQkOCIJ/2t/Ag+UsNLJsdHfpAgMBAAGjUzBR
  MB0GA1UdDgQWBBQZKCCS5kh2OxH6rPvwopd4hpDu4DAfBgNVHSMEGDAWgBQZKCCS
  5kh2OxH6rPvwopd4hpDu4DAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
  A4ICAQCsSZXxJ60Iz4O1WJ0ztoYVx/5tKAM88k/yA0Ey6kvEV5HfYp8fn4sTdbxd
  FdNy1zkuTkdPFSO1gN3CuJI1OscI0iqxd4KR9db7yWmg1de/0W+Ttu2X6zBx+JSk
  nPTnBtdIAwoP+HsqL8uOnbtl5nYcNeKX6fpafEIhCxPLj3gBU9lTyy2i9Pil1ZF4
  A3dhjmZ97Y8dNGibGomJdLxMRs6rRzVa0JqsHvK9SygufzzwPlzAe/cUhRjkUBHT
  M6nt4phKygeKgc89ypGgl8kTsfyINBpJFSCvLo3Kinu8N22hBEhs+s7w/Ko27EE/
  CeDNCnQR6bGTNqAzCSyxg4y/C1MEQXyXLBArLXFVfh7HPSizkV/1DiHjLImcwzVM
  tX/aOzH/oeG0AIBdx9Q0/xNkB/WNzy860Zl1AsZJCluzXA3jYo/KUzRAZ6zxoSAk
  4HPiYJOvR4XvYktjtHDDOgW9ZPpw39pHRNdgSfkjXMq/wxm7+LDq9ldsJmIOKjmY
  L7AZRU5hNbh7Gqk8OJ4M2O++1VoA250ZGf3hU5YYsSfLmDcWoTb0+JU5UfA1b4Ok
  WFt5UDur6pBP+GOQ1+IEkcRIYWR9NUSiKgGAAA0CWqouCDXssl9CxIUAwtaslxh0
  5HTPgO+Fpt8WTpZZYyWr1lkefB/u7I0qer3jeRTrWF05Sz25ow==
  -----END CERTIFICATE-----
pullSecret: '{"auths":{"support.ocp.kahvi.online:5000":{"auth":"YWVyZGVpOnIzZGg0dA=="}}}'
imageContentSources:
- mirrors:
  - support.ocp.kahvi.online:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - support.ocp.kahvi.online:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLuvuHUjSevVAlzxkDF4CpmN0VBcFkUh6FpF0H/RTTFlCbwQ0T8hgULEi5HVoomV8YuffksrZ+byQBOAd7QalIIO9KZXO0GXMpmGRqJGQyAUhw7OYaHvS4TrY8H4rMVXCcysI+CrA32kBXmMwX8WEE+jhDEBZvVWgVzgKSx8UNvxRlErMLq5VRSYMszqIIxqvHBtLDdpz2ZyJV4AJcfZepG2hpzgHEsXw3HY3ipAreXe80dJhmJaAzStAsqh4ucs+BHbBzhgqETMFfSFMKz40kwv5Km8rjOKYf4t3bC0RYWm/JtdtVGmE04rgUPtuRyU5oc1MAVkyDwEe73qrHKOzp root@support.ocp.kahvi.online'
